feat: add documents
ministero-salute/it-dgc-verificac19-sdk-onboarding pull request #17
Opened 2021-12-29 16:55 UTC by astagi

2021-12-29 16:57 UTC, ministerosalute requested changes

2021-12-29 16:57 UTC, ministerosalute commented on README.md
> +# Documenti
@astagi ottimo lavoro! Potresti metterle sotto alla sezione `Specifiche tecniche` magari con un heading `##`? Grazie molte

2021-12-29 17:16 UTC, astagi commented
fatto @ministerosalute

2021-12-29 17:17 UTC, astagi commented on README.md
> +# Documenti
fatto @ministerosalute

2021-12-30 08:13 UTC, ministerosalute approved these changes

2021-12-30 08:13 UTC, merged