Inserimento herald-si/verificac19-sdk-php
ministero-salute/it-dgc-verificac19-sdk-onboarding pull request #2
Opened 2021-11-09 08:42 UTC by herald-si

Come da README, è stata inserita una riga per la libreria herald-si/verificac19-sdk-php

2021-11-17 16:25 UTC, DevPGS commented
rilasciata nuova versione dell'SDK
https://github.com/herald-si/verificac19-sdk-php/releases/tag/v1.0.3

2021-11-18 09:22 UTC, ministerosalute requested changes
Grazie @herald-si @DevPGS per l'ultima release. 
Piccolo bump di data per poter procedere al merge.

2021-11-18 09:22 UTC, ministerosalute commented on README.md
> +| herald-si/verificac19-sdk-php| PHP| https://github.com/herald-si/verificac19-sdk-php | 09/11/2021 |
```suggestion
| herald-si/verificac19-sdk-php| PHP| https://github.com/herald-si/verificac19-sdk-php | 18/11/2021 |
```

2021-11-18 09:25 UTC, DevPGS approved these changes

2021-11-18 09:31 UTC, merged

2021-11-18 09:31 UTC, ministerosalute commented
Grazie @herald-si e @DevPGS.