chore: add verificac19-sdk for Node.js
ministero-salute/it-dgc-verificac19-sdk-onboarding pull request #3
Opened 2021-11-09 10:09 UTC by astagi

2021-12-07 08:32 UTC, luca-vix commented
Buongiorno, volevamo sapere quando questa libre

2021-12-07 08:35 UTC, luca-vix commented
Buongiorno @ministerosalute e @astagi, 
avremmo bisogno di questa libreria per dei sistemi di verifica dei green pass e volevamo chiedervi se possibile sapere quando questa verrà approvata e inserita nella lista ufficiale.
Grazie mille e buon lavoro a tutti.

2021-12-07 09:28 UTC, Angrigo commented
Rilasciare ufficialmente solo per le piattaforme native è un po' una dittatura, free nodejs code now @ministerosalute

2021-12-07 10:20 UTC, dcannova commented
Secondo me hanno approvato quella php e se ne sono fregati.
Avevo tirato su un castello per integrare nodejs nei sistemi utili all'azienda per la quale lavoro e poi ho dovuto mettere tutto da parte non appena è stata accettata la versione php.
Che abbia in più o in meno alla versione node mi è oscuro.

https://github.com/ministero-salute/dcc-utils/issues/16

2021-12-07 11:36 UTC, GGB1977 commented
Buongiorno @ministerosalute, siamo in attesa della vostra review per la versione Node.js da qualche tempo per rilasciare l'aggiornamento del nostro sistema di verifica accessi aziendale... è possibile sapere quanto tempo ci vuole ancora?

No so quali passaggi e test comporto la vostra approvazione, dal canto nostro vi possiamo garantire che il progetto Node,js funziona alla grande, scarico regole/chiavi e black, verifica dei green pass, opzione per GP rafforzato, non manca nulla attendiamo solo voi...    ;)

2021-12-08 12:00 UTC, ministerosalute commented
Buongiorno @astagi, sarebbe possibile effettuare un rebase per allineare con l'attuale `main`? In questo modo possiamo procedere con il merge. Grazie molte

2021-12-08 13:28 UTC, astagi commented
@ministerosalute fatto!

2021-12-08 15:07 UTC, ministerosalute commented
Perfetto @astagi, procedo con il merge. Grazie molte

2021-12-08 15:09 UTC, ministerosalute requested changes

2021-12-08 15:09 UTC, ministerosalute commented on README.md
> +| verificac19-sdk   | Node.js | https://github.com/italia/verificac19-sdk      | 08/12/2021    |
@astagi sarebbe possibile inserire questa nuova entry come ultima riga? Giusto per rispettare l'ordine di inserimento in tabella, grazie.

2021-12-08 15:43 UTC, astagi commented
@ministerosalute fatto grazie!

2021-12-08 15:45 UTC, ministerosalute approved these changes
:+1:

2021-12-08 15:45 UTC, merged