Aggiunta di DgcReader per .NET / .NET Framework
ministero-salute/it-dgc-verificac19-sdk-onboarding pull request #4
Opened 2021-11-09 20:36 UTC by DevTrevi

2021-11-12 14:41 UTC, KeyserDSoze commented
Quanto tempo ci vuole per la certificazione o approvazione? Potrà essere possibile utilizzarla ad esempio per settimana prossima?

2021-11-12 21:25 UTC, ElettroAle commented
> Quanto tempo ci vuole per la certificazione o approvazione? Potrà essere possibile utilizzarla ad esempio per settimana prossima?

Quoto, sarebbe gradita una rapida approvazione.

2021-11-15 07:57 UTC, MarGraz commented
Mi accodo alla richiesta. DgcReader è fondamentale in ambito .NET. Tra quanto tempo sarà reso disponibile?

2021-11-15 08:07 UTC, MACEL94 commented
Anche per me sarebbe fondamentale sapere quanto prima il tempo di attesa per l'accettazione di questa PR.

Grazie

2021-11-17 16:43 UTC, FedeInMarte commented
Ancora nessuna news? Non vorrei che il codice fosse approvato quando non serve più....

2021-12-07 18:04 UTC, ministerosalute requested changes

2021-12-07 18:04 UTC, ministerosalute commented on README.md
> +| DgcReader      | .NET / .NET Framework | https://github.com/DevTrevi/DgcReader | 09/11/2021 |
```suggestion
| DgcReader      | .NET / .NET Framework | https://github.com/DevTrevi/DgcReader | 07/12/2021 |
```

2021-12-07 18:06 UTC, ministerosalute commented
Buonasera @DevTrevi,
è possibile fare un rebase per allineare il fork con upstream e sistemare la data con quella odierna? Fatto questo potremo effettuare il merge. Grazie molte

2021-12-08 11:46 UTC, DevTrevi commented
Buongiorno @ministerosalute, mi scuso per il ritardo, ho modificato la data e allineato il fork come richiesto.
Vi ringrazio, buona giornata a tutti

2021-12-08 11:58 UTC, ministerosalute commented
Grazie @DevTrevi, perfetto, procediamo con il merge.

2021-12-08 11:59 UTC, merged