Adding hrnext/it-dgc-verificac19-spring
ministero-salute/it-dgc-verificac19-sdk-onboarding pull request #8
Opened 2021-11-18 18:13 UTC by marcoserafini2

Adding hrnext/it-dgc-verificac19-spring to the list

2021-12-15 20:39 UTC, ministerosalute commented
Buonasera @marcoserafini2, è possibile fare un rebase e inserire la data odierna? In questo modo possiamo procedere con il merge. Grazie molte

2021-12-16 08:17 UTC, marcoserafini2 commented
Buongiorno @ministerosalute rebase effettuata. Grazie

2021-12-16 08:40 UTC, ministerosalute requested changes

2021-12-16 08:40 UTC, ministerosalute commented on README.md
> +| hrnext/it-dgc-verificac19-spring | Java/Spring | https://github.com/hrnext/it-dgc-verificac19-spring | 17/12/2021 |
```suggestion
| hrnext/it-dgc-verificac19-spring | Java/Spring | https://github.com/hrnext/it-dgc-verificac19-spring | 16/12/2021 |
```

2021-12-16 08:40 UTC, ministerosalute commented
Grazie @marcoserafini2, è possibile cambiare data al 16/12? Grazie

2021-12-16 08:59 UTC, ministerosalute approved these changes

2021-12-16 08:59 UTC, ministerosalute commented
Perfetto, procedo con il merge, grazie molte @marcoserafini2

2021-12-16 09:00 UTC, merged